services:
  optidigital-test:
    build:
      context: vue-app
    container_name: optidigital-test
    restart: always
    ports:
      - '8080:8080'
    volumes:
      - '${PWD}:/app'
      - '${PWD}/cert.pem:/app/cert.pem'
      - '${PWD}/key.pem:/app/key.pem'
      - /app/node_modules
      - /app/dist
    networks:
      - vue-network
networks:
  vue-network:
    driver: bridge
